version: '2.3'

services:
  typeeasy:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./typeeasycode:/code
    working_dir: /code
    entrypoint: ["/typeeasy/typeeasy"]
