name: Save traffic statistics

on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch: 

jobs:
  save_traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      - name: Save clones and views data
        uses: joshcarp/traffic-lite@v2.0.0
        with:
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .github/traffic-history.json
      
      - name: Create empty file if it doesn't exist
        run: |
          if [ ! -f .github/traffic-history.json ]; then
            echo '[]' > .github/traffic-history.json
          fi
      
      - name: Commit and push the file to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update traffic history"
          file_pattern: .github/traffic-history.json